version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'faztpassword'
      MYSQL_DATABASE: 'flaskcrud'
    ports:
      - "3307:3306"
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql

  flask-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: faztpassword
      MYSQL_DB: flaskcrud
      MYSQL_PORT: 3306